name: build for test
on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY_ID }}
        run: |
          aws s3 rm s3://${{ secrets.AWS_S3_BUCKET_NAME_TEST }} \
            --recursive \
            --region ap-northeast-2
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME_TEST }}
      - name: Cloudfront Invalidate
        uses: awact/cloudfront-action@master
        env:
          SOURCE_PATH: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY_ID }}
          DISTRIBUTION_ID: ${{ secrets.AWS_CF_DISTRIBUTION_ID_TEST }}
